//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_clima.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimaCiudad
    {
        public int id { get; set; }
        public int idCiudad { get; set; }
        public int idClima { get; set; }
        public Nullable<int> tempmax { get; set; }
        public Nullable<int> tempmin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
